# Go Agent Configuration

# Agent configuration
agent:
  name: "Go-Agent"
  role_description: "Intelligent agent for task planning and execution"
  max_steps: [5, 3, 2]  # Multi-level planning depth
  max_rounds: 10
  parallel: false

# LLM provider configuration
llm:
  provider: "deepseek-personal"  # deepseek-personal, openai, mock
  model: "deepseek-chat"
  temperature: 0.7
  max_tokens: 4096
  api_key: "sk-4ad2357f8ed3483ca32d278f0b5d5ebe"  # DeepSeek personal API key
  base_url: "https://api.deepseek.com"            # DeepSeek personal API endpoint

# Execution configuration
execution:
  timeout: 30  # seconds
  output_dir: "./output"

# Tool configuration
tools:
  enabled:
    - "calculator"
    - "file"
    - "search"

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  file: "./logs/agent.log"